services:
  app:
    image: node:18-alpine
    restart: always
    working_dir: /app
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "5555:5555" # prisma studio
    volumes:
      - .:/app
    command: >
      sh -c "npm install && npx prisma db push && (npx prisma studio &) && npm run dev"
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
